version: '3.1'

services:

   mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dave
      MONGO_INITDB_ROOT_PASSWORD: pass1
    ports:
       - '127.0.0.1:27017:27017'
    network_mode: "host"

   keyboard:
      build: .
      container_name: keyboard
      depends_on:
        - mongo
      ports:
      - '127.0.0.1:8080:8080'
      network_mode: "host"
